name: Clangen CI/CD
on: push

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: "brew install python-tk@3.10"
      - run: "pip3 install -r requirements.txt"
      - run: "pip3 install pyinstaller pillow"
      - run: "pyinstaller Clangen.spec"
      - run: "rm -r dist/Clangen"
      - run: "codesign --force --sign - dist/Clangen.app"
      - run: "npm install -g appdmg"
      - run: "appdmg appdmg.json Clangen.dmg"
      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: Clangen.dmg
