name: PyInstaller build

on: [push]

jobs:
  build_linux64:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11 x64
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Install depends
        run: python -m pip install --pre pygame ujson pygame mock
      - name: Run pytest
        env:
          SDL_VIDEODRIVER: "dummy"
          SDL_AUDIODRIVER: "disk"
        run: python3 -m unittest tests/test_cat.py
